<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="2" tests="20" name="testcases.TC_WarDeployment" time="293.369" errors="0" timestamp="2024-04-11T10:25:10 IST" skipped="0">
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="25.340"/>
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="17.680"/>
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="25.891">
    <failure message="expected [INSUFFICIENT FUNDS] but found [APPROVAL]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [INSUFFICIENT FUNDS] but found [APPROVAL]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testcases.TC_WarDeployment.testSale(TC_WarDeployment.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSale -->
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="17.559">
    <failure message="expected [INSUFFICIENT FUNDS] but found [APPROVAL]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [INSUFFICIENT FUNDS] but found [APPROVAL]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testcases.TC_WarDeployment.testSale(TC_WarDeployment.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSale -->
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="19.888"/>
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="24.306"/>
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="17.106"/>
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="25.565"/>
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="15.583"/>
  <testcase classname="testcases.TC_WarDeployment" name="testSale" time="16.679"/>
  <testcase classname="testcases.TC_WarDeployment" name="delayTime" time="5.319"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="5.872"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="10.004"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="10.072"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="10.484"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="10.184"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="10.241"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="10.253"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="10.105"/>
  <testcase classname="testcases.TC_WarDeployment" name="testAllVoidTransactions" time="5.238"/>
</testsuite> <!-- testcases.TC_WarDeployment -->
